// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/22/2026, 12:18:43 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/kimlarocca/Websites/dearest-jack/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimlarocca/Websites/dearest-jack/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimlarocca/Websites/dearest-jack/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimlarocca/Websites/dearest-jack/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kimlarocca/Websites/dearest-jack/plugins/**/*.{js,ts,mjs}","/Users/kimlarocca/Websites/dearest-jack/composables/**/*.{js,ts,mjs}","/Users/kimlarocca/Websites/dearest-jack/utils/**/*.{js,ts,mjs}","/Users/kimlarocca/Websites/dearest-jack/pages/index.vue","/Users/kimlarocca/Websites/dearest-jack/pages/privacy.vue","/Users/kimlarocca/Websites/dearest-jack/pages/styleguide.vue","/Users/kimlarocca/Websites/dearest-jack/pages/terms.vue","/Users/kimlarocca/Websites/dearest-jack/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kimlarocca/Websites/dearest-jack/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kimlarocca/Websites/dearest-jack/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;